// Real saved suite only. No test data or findings are generated by this UI check.
const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE,args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.SHADECHECK_DASHBOARD_URL);
  await page.locator('#workspace').waitFor({state:'visible'});
  const data=await page.evaluate(()=>fetch('/api/data').then(r=>r.json()));
  assert.equal(data.suite.acceptance_status,'PASS');assert.equal(data.suite.privacy_status,'FAIL');
  assert.equal(Number(await page.locator('#count').textContent()),data.reports.length);
  await page.selectOption('#status','PASS');
  assert.equal(await page.locator('.report-item').count(),data.reports.filter(r=>r.result.status==='PASS').length);
  await page.selectOption('#status','all');await page.selectOption('#rule','SC-005');
  await page.locator('.report-item').filter({hasText:'severity-increase'}).click();
  await page.locator('summary').filter({hasText:'Current evidence'}).last().click();
  const report=data.reports.find(r=>r.path.endsWith('severity-increase.json'));
  const comparison=report.result.baseline_comparison;
  assert.equal(comparison.changes[0].previous_severity,'MEDIUM');assert.equal(comparison.changes[0].current_severity,'HIGH');
  assert.ok((await page.locator('#detail').textContent()).includes('MEDIUM → HIGH'));
  assert.ok((await page.locator('#detail').textContent()).includes(report.result.evidence_root));
  const event=report.result.findings.at(-1).evidence.find(e=>e.timestamp_ns);
  assert.equal(typeof event.timestamp_ns,'string');assert.ok((await page.locator('#detail').textContent()).includes(event.timestamp_ns));
  const download=await Promise.all([page.waitForEvent('download'),page.locator('#detail a').filter({hasText:'JSON'}).click()]);
  await download[0].saveAs(process.env.SHADECHECK_SCREENSHOT_DIR+'/downloaded-report.json');
  await page.screenshot({path:process.env.SHADECHECK_SCREENSHOT_DIR+'/dashboard-desktop.png',fullPage:true});
  await page.locator('[data-tab="rules"]').click();assert.equal(await page.locator('.rule-card').count(),5);
  await page.locator('[data-tab="artifacts"]').click();assert.equal(await page.locator('.artifact-row').count(),data.artifacts.length);
  await page.locator('[data-tab="reports"]').click();
  await page.fill('#search','there-is-no-such-report');assert.equal(await page.locator('.report-item').count(),0);
  await page.fill('#search','');await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:process.env.SHADECHECK_SCREENSHOT_DIR+'/dashboard-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('REAL DASHBOARD BROWSER CHECK VERIFIED: filters, findings, exact timestamp strings, baseline escalation, downloads, rule library, artifacts, responsive layout.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
